<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icon\XFEToolBoxIcon.ico</ApplicationIcon>
    <Version>0.2.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icon\XFEToolBoxIcon.ico" />
    <None Remove="Resources\Icon\XFEToolBoxLogo.png" />
    <None Remove="Resources\Icon\XFEToolBoxSplashScreen.png" />
    <None Remove="Resources\Image\back.png" />
    <None Remove="Resources\Image\check.png" />
    <None Remove="Resources\Image\clean.png" />
    <None Remove="Resources\Image\close.png" />
    <None Remove="Resources\Image\console.png" />
    <None Remove="Resources\Image\corner.png" />
    <None Remove="Resources\Image\download.png" />
    <None Remove="Resources\Image\DownloadImage\cheat_engine.png" />
    <None Remove="Resources\Image\DownloadImage\steampp.png" />
    <None Remove="Resources\Image\DownloadImage\visualstudio.png" />
    <None Remove="Resources\Image\DownloadImage\visual_studio.png" />
    <None Remove="Resources\Image\grid.png" />
    <None Remove="Resources\Image\invisible.png" />
    <None Remove="Resources\Image\min.png" />
    <None Remove="Resources\Image\restart.png" />
    <None Remove="Resources\Image\setting.png" />
    <None Remove="Resources\Image\start.png" />
    <None Remove="Resources\Image\steam_logo.png" />
    <None Remove="Resources\Image\stop.png" />
    <None Remove="Resources\Image\tabline.png" />
    <None Remove="Resources\Image\toolbox.png" />
    <None Remove="Resources\Image\visible.png" />
    <None Remove="Resources\Image\wrench.png" />
    <None Remove="Resources\Image\wrenchtool.png" />
    <None Remove="Resources\Image\wrench_tool.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="XFEExtension.NetCore" Version="3.3.10" />
    <PackageReference Include="XFEExtension.NetCore.AutoConfig" Version="2.0.7" />
    <PackageReference Include="XFEExtension.NetCore.AutoPath" Version="1.0.1" />
    <PackageReference Include="XFEExtension.NetCore.InputSimulator" Version="2.3.0" />
    <PackageReference Include="XFEExtension.NetCore.TodoHighLight" Version="1.0.0" />
    <PackageReference Include="XFEExtension.NetCore.XFEConsole" Version="1.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icon\XFEToolBoxIcon.ico" />
    <Resource Include="Resources\Icon\XFEToolBoxLogo.png" />
    <Resource Include="Resources\Image\back.png" />
    <Resource Include="Resources\Image\check.png" />
    <Resource Include="Resources\Image\clean.png" />
    <Resource Include="Resources\Image\close.png" />
    <Resource Include="Resources\Image\console.png" />
    <Resource Include="Resources\Image\corner.png" />
    <Resource Include="Resources\Image\download.png" />
    <Resource Include="Resources\Image\DownloadImage\cheat_engine.png" />
    <Resource Include="Resources\Image\DownloadImage\steampp.png" />
    <Resource Include="Resources\Image\DownloadImage\visual_studio.png" />
    <Resource Include="Resources\Image\grid.png" />
    <Resource Include="Resources\Image\invisible.png" />
    <Resource Include="Resources\Image\min.png" />
    <Resource Include="Resources\Image\restart.png" />
    <Resource Include="Resources\Image\setting.png" />
    <Resource Include="Resources\Image\start.png" />
    <Resource Include="Resources\Image\DownloadImage\steam_logo.png" />
    <Resource Include="Resources\Image\stop.png" />
    <Resource Include="Resources\Image\tabline.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Profiles\CurrentVersionProfiles\" />
    <Folder Include="Profiles\SynProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XFEToolBox.Core\XFEToolBox.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icon\XFEToolBoxSplashScreen.png" />
    <Resource Include="Resources\Image\toolbox.png" />
    <Resource Include="Resources\Image\visible.png" />
    <Resource Include="Resources\Image\wrench.png" />
    <Resource Include="Resources\Image\wrench_tool.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Resource\DownloadInfoResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DownloadInfoResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource\DownloadInfoResource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DownloadInfoResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
