<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\Icon\XFEToolBoxIcon.ico</ApplicationIcon>
    <Version>1.1.5</Version>
    <AssemblyTitle>XFEToolBox</AssemblyTitle>
    <AssemblyName>XFEToolBox</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icon\XFEToolBoxIcon.ico" />
    <None Remove="Resources\Icon\XFEToolBoxLogo.png" />
    <None Remove="Resources\Icon\XFEToolBoxSplashScreen.png" />
    <None Remove="Resources\Image\back.png" />
    <None Remove="Resources\Image\clean.png" />
    <None Remove="Resources\Image\console.png" />
    <None Remove="Resources\Image\download.png" />
    <None Remove="Resources\Image\default_tool_icon.png" />
    <None Remove="Resources\Image\DownloadImage\cheat_engine.png" />
    <None Remove="Resources\Image\DownloadImage\steampp.png" />
    <None Remove="Resources\Image\DownloadImage\visualstudio.png" />
    <None Remove="Resources\Image\DownloadImage\visual_studio.png" />
    <None Remove="Resources\Image\grid.png" />
    <None Remove="Resources\Image\restart.png" />
    <None Remove="Resources\Image\setting.png" />
    <None Remove="Resources\Image\start.png" />
    <None Remove="Resources\Image\steam_logo.png" />
    <None Remove="Resources\Image\stop.png" />
    <None Remove="Resources\Image\toolbox.png" />
    <None Remove="Resources\Image\wrench.png" />
    <None Remove="Resources\Editor\**\*" />
    <None Remove="Resources\ChatCall\**\*" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.995" />
    <PackageReference Include="Markdig" Version="1.3.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <PackageReference Include="XFEExtension.NetCore" Version="5.2.1" />
    <PackageReference Include="XFEExtension.NetCore.AutoConfig" Version="4.1.2" />
    <PackageReference Include="XFEExtension.NetCore.AutoPath" Version="2.0.0" />
    <PackageReference Include="XFEExtension.NetCore.InputSimulator" Version="2.3.0" />
    <PackageReference Include="XFEExtension.NetCore.TodoHighLight" Version="1.0.0" />
    <PackageReference Include="XFEExtension.NetCore.UpgradeHelper" Version="2.0.0" />
    <PackageReference Include="XFEExtension.NetCore.XFEConsole" Version="2.6.0" Condition="'$(UseLocalXFEConsoleSource)' != 'true'" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icon\XFEToolBoxIcon.ico" />
    <Resource Include="Resources\Icon\XFEToolBoxLogo.png" />
    <Resource Include="Resources\Image\back.png" />
    <Resource Include="Resources\Image\clean.png" />
    <Resource Include="Resources\Image\console.png" />
    <Resource Include="Resources\Image\download.png" />
    <Resource Include="Resources\Image\default_tool_icon.png" />
    <Resource Include="Resources\Image\DownloadImage\cheat_engine.png" />
    <Resource Include="Resources\Image\DownloadImage\steampp.png" />
    <Resource Include="Resources\Image\DownloadImage\visual_studio.png" />
    <Resource Include="Resources\Image\grid.png" />
    <Resource Include="Resources\Image\restart.png" />
    <Resource Include="Resources\Image\setting.png" />
    <Resource Include="Resources\Image\start.png" />
    <Resource Include="Resources\Image\DownloadImage\steam_logo.png" />
    <Resource Include="Resources\Image\stop.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Profiles\CurrentVersionProfiles\" />
    <Folder Include="Profiles\SynProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XFEToolBox.Client.Core\XFEToolBox.Client.Core.csproj" />
    <ProjectReference Include="..\XFEToolBox.Core\XFEToolBox.Core.csproj" />
    <ProjectReference Include="..\XFEToolBox.WpfCore\XFEToolBox.WpfCore.csproj" />
    <ProjectReference Include="..\..\XFEExtension.NetCore.XFEConsole\XFEExtension.NetCore.XFEConsole\XFEExtension.NetCore.XFEConsole.csproj" Condition="'$(UseLocalXFEConsoleSource)' == 'true'" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="XFEToolBox.Client.Wpf.Test" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Editor\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\ChatCall\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icon\XFEToolBoxSplashScreen.png" />
    <Resource Include="Resources\Image\toolbox.png" />
    <Resource Include="Resources\Image\wrench.png" />
  </ItemGroup>

</Project>
