using System.Collections.Specialized;
using System.Windows;
using System.Windows.Controls;

namespace XFEToolBox.WpfCore.Controls;

/// <summary>
/// 让 DataGrid 内置列生成的控件也复用应用级统一样式。
/// WPF 会为 DataGridComboBoxColumn、DataGridCheckBoxColumn 等列主动指定系统样式，
/// 因此单纯的隐式控件样式无法覆盖这些生成元素。
/// </summary>
public static class DataGridAssist
{
    public static readonly DependencyProperty UseUnifiedCellControlsProperty = DependencyProperty.RegisterAttached(
        "UseUnifiedCellControls",
        typeof(bool),
        typeof(DataGridAssist),
        new FrameworkPropertyMetadata(false, OnUseUnifiedCellControlsChanged));

    public static readonly DependencyProperty ComboBoxElementStyleProperty = RegisterStyleProperty("ComboBoxElementStyle");
    public static readonly DependencyProperty ComboBoxEditingStyleProperty = RegisterStyleProperty("ComboBoxEditingStyle");
    public static readonly DependencyProperty CheckBoxElementStyleProperty = RegisterStyleProperty("CheckBoxElementStyle");
    public static readonly DependencyProperty CheckBoxEditingStyleProperty = RegisterStyleProperty("CheckBoxEditingStyle");
    public static readonly DependencyProperty TextElementStyleProperty = RegisterStyleProperty("TextElementStyle");
    public static readonly DependencyProperty TextEditingStyleProperty = RegisterStyleProperty("TextEditingStyle");

    private static readonly DependencyProperty ColumnsChangedHandlerProperty = DependencyProperty.RegisterAttached(
        "ColumnsChangedHandler",
        typeof(NotifyCollectionChangedEventHandler),
        typeof(DataGridAssist),
        new PropertyMetadata(null));

    public static bool GetUseUnifiedCellControls(DependencyObject element) =>
        (bool)element.GetValue(UseUnifiedCellControlsProperty);

    public static void SetUseUnifiedCellControls(DependencyObject element, bool value) =>
        element.SetValue(UseUnifiedCellControlsProperty, value);

    public static Style? GetComboBoxElementStyle(DependencyObject element) =>
        (Style?)element.GetValue(ComboBoxElementStyleProperty);

    public static void SetComboBoxElementStyle(DependencyObject element, Style? value) =>
        element.SetValue(ComboBoxElementStyleProperty, value);

    public static Style? GetComboBoxEditingStyle(DependencyObject element) =>
        (Style?)element.GetValue(ComboBoxEditingStyleProperty);

    public static void SetComboBoxEditingStyle(DependencyObject element, Style? value) =>
        element.SetValue(ComboBoxEditingStyleProperty, value);

    public static Style? GetCheckBoxElementStyle(DependencyObject element) =>
        (Style?)element.GetValue(CheckBoxElementStyleProperty);

    public static void SetCheckBoxElementStyle(DependencyObject element, Style? value) =>
        element.SetValue(CheckBoxElementStyleProperty, value);

    public static Style? GetCheckBoxEditingStyle(DependencyObject element) =>
        (Style?)element.GetValue(CheckBoxEditingStyleProperty);

    public static void SetCheckBoxEditingStyle(DependencyObject element, Style? value) =>
        element.SetValue(CheckBoxEditingStyleProperty, value);

    public static Style? GetTextElementStyle(DependencyObject element) =>
        (Style?)element.GetValue(TextElementStyleProperty);

    public static void SetTextElementStyle(DependencyObject element, Style? value) =>
        element.SetValue(TextElementStyleProperty, value);

    public static Style? GetTextEditingStyle(DependencyObject element) =>
        (Style?)element.GetValue(TextEditingStyleProperty);

    public static void SetTextEditingStyle(DependencyObject element, Style? value) =>
        element.SetValue(TextEditingStyleProperty, value);

    private static DependencyProperty RegisterStyleProperty(string name) =>
        DependencyProperty.RegisterAttached(
            name,
            typeof(Style),
            typeof(DataGridAssist),
            new FrameworkPropertyMetadata(null, OnCellControlStyleChanged));

    private static void OnUseUnifiedCellControlsChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs args)
    {
        if (dependencyObject is not DataGrid dataGrid)
            return;

        if ((bool)args.NewValue)
        {
            dataGrid.Loaded += DataGrid_Loaded;
            dataGrid.AutoGeneratedColumns += DataGrid_AutoGeneratedColumns;

            if (dataGrid.GetValue(ColumnsChangedHandlerProperty) is not NotifyCollectionChangedEventHandler handler)
            {
                handler = (_, _) => ApplyColumnStyles(dataGrid);
                dataGrid.SetValue(ColumnsChangedHandlerProperty, handler);
                dataGrid.Columns.CollectionChanged += handler;
            }

            ApplyColumnStyles(dataGrid);
        }
        else
        {
            dataGrid.Loaded -= DataGrid_Loaded;
            dataGrid.AutoGeneratedColumns -= DataGrid_AutoGeneratedColumns;

            if (dataGrid.GetValue(ColumnsChangedHandlerProperty) is NotifyCollectionChangedEventHandler handler)
            {
                dataGrid.Columns.CollectionChanged -= handler;
                dataGrid.ClearValue(ColumnsChangedHandlerProperty);
            }
        }
    }

    private static void OnCellControlStyleChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs args)
    {
        if (dependencyObject is DataGrid dataGrid && GetUseUnifiedCellControls(dataGrid))
            ApplyColumnStyles(dataGrid);
    }

    private static void DataGrid_Loaded(object sender, RoutedEventArgs e)
    {
        if (sender is DataGrid dataGrid)
            ApplyColumnStyles(dataGrid);
    }

    private static void DataGrid_AutoGeneratedColumns(object? sender, EventArgs e)
    {
        if (sender is DataGrid dataGrid)
            ApplyColumnStyles(dataGrid);
    }

    private static void ApplyColumnStyles(DataGrid dataGrid)
    {
        foreach (var column in dataGrid.Columns)
        {
            switch (column)
            {
                case DataGridComboBoxColumn comboBoxColumn:
                    ApplyStylesIfUnset(
                        comboBoxColumn,
                        GetComboBoxElementStyle(dataGrid),
                        GetComboBoxEditingStyle(dataGrid));
                    break;

                case DataGridCheckBoxColumn checkBoxColumn:
                    ApplyStylesIfUnset(
                        checkBoxColumn,
                        GetCheckBoxElementStyle(dataGrid),
                        GetCheckBoxEditingStyle(dataGrid));
                    break;

                case DataGridTextColumn textColumn:
                    ApplyStylesIfUnset(
                        textColumn,
                        GetTextElementStyle(dataGrid),
                        GetTextEditingStyle(dataGrid));
                    break;

                case DataGridHyperlinkColumn hyperlinkColumn:
                    ApplyStylesIfUnset(
                        hyperlinkColumn,
                        GetTextElementStyle(dataGrid),
                        null);
                    break;
            }
        }
    }

    private static void ApplyStylesIfUnset(DataGridBoundColumn column, Style? elementStyle, Style? editingStyle)
    {
        // 显式设置的列样式代表页面作者的主动选择，只替换 WPF 自动回退的系统默认样式。
        if (column.ElementStyle is null && elementStyle is not null)
            column.ElementStyle = elementStyle;

        if (column.EditingElementStyle is null && editingStyle is not null)
            column.EditingElementStyle = editingStyle;
    }

    private static void ApplyStylesIfUnset(DataGridComboBoxColumn column, Style? elementStyle, Style? editingStyle)
    {
        // DataGridComboBoxColumn 不继承 DataGridBoundColumn，但拥有独立的同名样式属性。
        if (column.ElementStyle is null && elementStyle is not null)
            column.ElementStyle = elementStyle;

        if (column.EditingElementStyle is null && editingStyle is not null)
            column.EditingElementStyle = editingStyle;
    }
}
