<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XFEExtension.NetCore" Version="5.1.0" />
    <PackageReference Include="XFEExtension.NetCore.AutoConfig" Version="3.0.1" />
    <PackageReference Include="XFEExtension.NetCore.AutoPath" Version="2.0.0" />
    <PackageReference Include="XFEExtension.NetCore.TodoHighLight" Version="1.0.0" />
  </ItemGroup>

</Project>
