//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFEToolBox.Client.Resources.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DownloadInfoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DownloadInfoResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XFEToolBox.Client.Resources.Resource.DownloadInfoResource", typeof(DownloadInfoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 URL:https://d1vdn3r1396bak.cloudfront.net/installer/615515/8160454381798 的本地化字符串。
        /// </summary>
        internal static string CheatEngine {
            get {
                return ResourceManager.GetString("CheatEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL:https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe 的本地化字符串。
        /// </summary>
        internal static string Steam {
            get {
                return ResourceManager.GetString("Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL:https://apps.microsoft.com/0d4d1483-85ee-45ff-a2ef-f5cad41db2c8 的本地化字符串。
        /// </summary>
        internal static string Steampp {
            get {
                return ResourceManager.GetString("Steampp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL:https://c2rsetup.officeapps.live.com/c2r/downloadVS.aspx?sku=community&amp;channel=Release&amp;version=VS2022&amp;source=VSLandingPage&amp;cid=2030:932d79d8269b49daac423040f7b7a9d4 的本地化字符串。
        /// </summary>
        internal static string VisualStudio {
            get {
                return ResourceManager.GetString("VisualStudio", resourceCulture);
            }
        }
    }
}
